//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFinanciera.ServicioFinancieraIndependiente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFinancieraIndependiente.IPoliticaOtorgamiento")]
    public interface IPoliticaOtorgamiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliticaOtorgamiento/GuardarPoliticaOtorgamiento", ReplyAction="http://tempuri.org/IPoliticaOtorgamiento/GuardarPoliticaOtorgamientoResponse")]
        int GuardarPoliticaOtorgamiento(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliticaOtorgamiento/GuardarPoliticaOtorgamiento", ReplyAction="http://tempuri.org/IPoliticaOtorgamiento/GuardarPoliticaOtorgamientoResponse")]
        System.Threading.Tasks.Task<int> GuardarPoliticaOtorgamientoAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPoliticaOtorgamientoChannel : WpfFinanciera.ServicioFinancieraIndependiente.IPoliticaOtorgamiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PoliticaOtorgamientoClient : System.ServiceModel.ClientBase<WpfFinanciera.ServicioFinancieraIndependiente.IPoliticaOtorgamiento>, WpfFinanciera.ServicioFinancieraIndependiente.IPoliticaOtorgamiento {
        
        public PoliticaOtorgamientoClient() {
        }
        
        public PoliticaOtorgamientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PoliticaOtorgamientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoliticaOtorgamientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoliticaOtorgamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GuardarPoliticaOtorgamiento(int numero) {
            return base.Channel.GuardarPoliticaOtorgamiento(numero);
        }
        
        public System.Threading.Tasks.Task<int> GuardarPoliticaOtorgamientoAsync(int numero) {
            return base.Channel.GuardarPoliticaOtorgamientoAsync(numero);
        }
    }
}
